config/routes.rb
Quanthicaweb::Application.routes.draw do

  resources :user_algorithm_subscriptions

  resources :brokers

  resources :markets

  resources :api_calls, except: [:new, :edit, :update]

  mount API::Base => '/api'
    
  resources :algorithms

  resources :profiles

  root to: "static_pages#home", via: [:get]
  match '/about', to: 'static_pages#about', via: [:get]
  match '/register_email', to: 'static_pages#register_email', via: [:post]
    
  devise_for :users
  scope '/admin' do
    resources :users
    resources :roles
  end
  

end

app/models/algorithm.rb
class Algorithm < ActiveRecord::Base
  
  include Approvable

  belongs_to :user
  scope :all_owned_by, ->(user) { where(:user_id => user.id)}

  has_many :user_algorithm_subscriptions, dependent: :destroy
  has_many :subscribed_users, :through => :user_algorithm_subscriptions, :source => :user

  validates_presence_of :name
  validates_uniqueness_of :name
end

app/controllers/algorithms_controller.rb
class AlgorithmsController < ApplicationController

  load_and_authorize_resource
  before_action :set_algorithm, only: [:show, :edit, :update, :destroy]

  # GET /algorithms
  # GET /algorithms.json
  def index
    Algorithm.all
  end

  # GET /algorithms/1
  # GET /algorithms/1.json
  def show
  end

  # GET /algorithms/new
  def new
    @algorithm = Algorithm.new
  end

  # GET /algorithms/1/edit
  def edit
  end

  # POST /algorithms
  # POST /algorithms.json
  def create
    @algorithm = Algorithm.new(algorithm_params)
    respond_to do |format|
      if @algorithm.save
        format.html { redirect_to @algorithm, notice: 'Algorithm was successfully created.' }
        format.json { render action: 'show', status: :created, location: @algorithm }
      else
        format.html { render action: 'new' }
        format.json { render json: @algorithm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /algorithms/1
  # PATCH/PUT /algorithms/1.json
  def update
    respond_to do |format|
      if @algorithm.update(algorithm_params)
        format.html { redirect_to @algorithm, notice: 'Algorithm was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @algorithm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /algorithms/1
  # DELETE /algorithms/1.json
  def destroy
    @algorithm.destroy
    respond_to do |format|
      format.html { redirect_to algorithms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_algorithm
      @algorithm = Algorithm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def algorithm_params
      params.require(:algorithm).permit(:user_id, :name, :approved)
    end

end

app/helpers/algorithms_helper.rb
module AlgorithmsHelper
end

app/views/algorithms/_form.html.erb
<%= form_for(@algorithm) do |f| %>
  <%= render 'shared/form_error_message_listing', object: f.object %>

  <% if current_user.has_role? :admin %>
    <div class="field">
      <%= f.label :user_id %><br>
      <%= f.collection_select :user_id, User.order('email ASC'), :id, :email, :include_blank => true %>
    </div>
  <% else %>  
    <%= hidden_field_tag "algorithm[user_id]", current_user.id %>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <% if current_user.has_role? :admin %>
    <div class="field">
      <%= f.label :approved %><br>
      <%= f.check_box :approved %>
    </div>
  <% end %>  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/algorithms/edit.html.erb
<h1>Editing algorithm</h1>

<%= render 'form' %>

<%= link_to 'Show', @algorithm %> |
<%= link_to 'Back', algorithms_path %>

app/views/algorithms/index.html.erb
<h1>Listing algorithms</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Approved</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @algorithms.each do |algorithm| %>
      <tr>
        <td><%= algorithm.user.email %></td>
        <td><%= algorithm.name %></td>
        <td><%= algorithm.approved %></td>
        <td><%= link_to 'Show', algorithm %></td>
        <td><%= link_to 'Edit', edit_algorithm_path(algorithm) %></td>
        <td><%= link_to 'Destroy', algorithm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Algorithm', new_algorithm_path %>

app/views/algorithms/new.html.erb
<h1>New algorithm</h1>

<%= render 'form' %>

<%= link_to 'Back', algorithms_path %>

app/views/algorithms/show.html.erb
<p>
  <strong>User:</strong>
  <%= @algorithm.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @algorithm.name %>
</p>

<p>
  <strong>Approved:</strong>
  <%= @algorithm.approved %>
</p>

<%= link_to 'Edit', edit_algorithm_path(@algorithm) %> |
<%= link_to 'Back', algorithms_path %>