config/routes.rb
Quanthicaweb::Application.routes.draw do

  resources :user_algorithm_subscriptions

  resources :brokers

  resources :markets

  resources :api_calls, except: [:new, :edit, :update]

  mount API::Base => '/api'
    
  resources :algorithms

  resources :profiles

  root to: "static_pages#home", via: [:get]
  match '/about', to: 'static_pages#about', via: [:get]
  match '/register_email', to: 'static_pages#register_email', via: [:post]
    
  devise_for :users
  scope '/admin' do
    resources :users
    resources :roles
  end
  

end

app/models/user_algorithm_subscription.rb
class UserAlgorithmSubscription < ActiveRecord::Base

  include Approvable

  belongs_to :user
  belongs_to :algorithm

  validates_presence_of :user_id, :algorithm_id
  validates_uniqueness_of :algorithm_id, :scope => :user_id
  
end

app/controllers/user_algorithm_subscriptions_controller.rb
class UserAlgorithmSubscriptionsController < ApplicationController

  load_and_authorize_resource
  before_action :set_user_algorithm_subscription, only: [:show, :edit, :update, :destroy]

  # GET /user_algorithm_subscriptions
  # GET /user_algorithm_subscriptions.json
  def index
    UserAlgorithmSubscription.all
  end

  # GET /user_algorithm_subscriptions/1
  # GET /user_algorithm_subscriptions/1.json
  def show
  end

  # GET /user_algorithm_subscriptions/new
  def new
    @user_algorithm_subscription = UserAlgorithmSubscription.new
  end

  # GET /user_algorithm_subscriptions/1/edit
  def edit
  end

  # POST /user_algorithm_subscriptions
  # POST /user_algorithm_subscriptions.json
  def create
    @user_algorithm_subscription = UserAlgorithmSubscription.new(user_algorithm_subscription_params)

    respond_to do |format|
      if @user_algorithm_subscription.save
        format.html { redirect_to @user_algorithm_subscription, notice: 'User algorithm subscription was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_algorithm_subscription }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_algorithm_subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_algorithm_subscriptions/1
  # PATCH/PUT /user_algorithm_subscriptions/1.json
  def update
    respond_to do |format|
      if @user_algorithm_subscription.update(user_algorithm_subscription_params)
        format.html { redirect_to @user_algorithm_subscription, notice: 'User algorithm subscription was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_algorithm_subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_algorithm_subscriptions/1
  # DELETE /user_algorithm_subscriptions/1.json
  def destroy
    @user_algorithm_subscription.destroy
    respond_to do |format|
      format.html { redirect_to user_algorithm_subscriptions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_algorithm_subscription
      @user_algorithm_subscription = UserAlgorithmSubscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_algorithm_subscription_params
      params.require(:user_algorithm_subscription).permit(:user_id, :algorithm_id, :approved)
    end
end

app/helpers/user_algorithm_subscriptions_helper.rb
module UserAlgorithmSubscriptionsHelper
end

app/views/user_algorithm_subscriptions/_form.html.erb
<%= form_for(@user_algorithm_subscription) do |f| %>
  <%= render 'shared/form_error_message_listing', object: f.object %>

  <% if current_user.has_role? :admin %>
    <div class="field">
      <%= f.label :user_id %><br>
      <%= f.collection_select :user_id, User.order('email ASC'), :id, :email, :include_blank => true %>
    </div>
  <% else %>  
    <%= hidden_field_tag "user_algorithm_subscription[user_id]", current_user.id %>
  <% end %>
  <div class="field">
    <%= f.label :algorithm_id %><br>
    <%= f.collection_select :algorithm_id, Algorithm.order('name ASC'), :id, :name, :include_blank => true %>
  </div>
  <% if current_user.has_role? :admin %>
    <div class="field">
      <%= f.label :approved %><br>
      <%= f.check_box :approved %>
    </div>
  <% end %> 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_algorithm_subscriptions/edit.html.erb
<h1>Editing user_algorithm_subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_algorithm_subscription %> |
<%= link_to 'Back', user_algorithm_subscriptions_path %>

app/views/user_algorithm_subscriptions/index.html.erb
<h1>Listing user_algorithm_subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Algorithm</th>
      <th>Approved</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_algorithm_subscriptions.each do |user_algorithm_subscription| %>
      <tr>
        <td><%= user_algorithm_subscription.user.profile.full_name %></td>
        <td><%= user_algorithm_subscription.algorithm.name %></td>
        <td><%= user_algorithm_subscription.approved %></td>
        <td><%= link_to 'Show', user_algorithm_subscription %></td>
        <td><%= link_to 'Edit', edit_user_algorithm_subscription_path(user_algorithm_subscription) %></td>
        <td><%= link_to 'Destroy', user_algorithm_subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User algorithm subscription', new_user_algorithm_subscription_path %>

app/views/user_algorithm_subscriptions/new.html.erb
<h1>New user_algorithm_subscription</h1>

<%= render 'form' %>

<%= link_to 'Back', user_algorithm_subscriptions_path %>

app/views/user_algorithm_subscriptions/show.html.erb
<p>
  <strong>User:</strong>
  <%= @user_algorithm_subscription.user.profile.full_name %>
</p>

<p>
  <strong>Algorithm:</strong>
  <%= @user_algorithm_subscription.algorithm.name %>
</p>

<p>
  <strong>Approved:</strong>
  <%= @user_algorithm_subscription.approved %>
</p>

<%= link_to 'Edit', edit_user_algorithm_subscription_path(@user_algorithm_subscription) %> |
<%= link_to 'Back', user_algorithm_subscriptions_path %>