config/routes.rb
Quanthicaweb::Application.routes.draw do

  resources :user_algorithm_subscriptions

  resources :brokers

  resources :markets

  resources :api_calls, except: [:new, :edit, :update]

  mount API::Base => '/api'
    
  resources :algorithms

  resources :profiles

  root to: "static_pages#home", via: [:get]
  match '/about', to: 'static_pages#about', via: [:get]
  match '/register_email', to: 'static_pages#register_email', via: [:post]
    
  devise_for :users
  scope '/admin' do
    resources :users
    resources :roles
  end
  

end

app/models/market.rb
class Market < ActiveRecord::Base
  validates_uniqueness_of :name

  has_many :brokers
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  
  load_and_authorize_resource
  before_action :set_market, only: [:show, :edit, :update, :destroy]

  # GET /markets
  # GET /markets.json
  def index
    @markets = Market.all
  end

  # GET /markets/1
  # GET /markets/1.json
  def show
  end

  # GET /markets/new
  def new
    @market = Market.new
  end

  # GET /markets/1/edit
  def edit
  end

  # POST /markets
  # POST /markets.json
  def create
    @market = Market.new(market_params)

    respond_to do |format|
      if @market.save
        format.html { redirect_to @market, notice: 'Market was successfully created.' }
        format.json { render action: 'show', status: :created, location: @market }
      else
        format.html { render action: 'new' }
        format.json { render json: @market.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /markets/1
  # PATCH/PUT /markets/1.json
  def update
    respond_to do |format|
      if @market.update(market_params)
        format.html { redirect_to @market, notice: 'Market was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @market.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /markets/1
  # DELETE /markets/1.json
  def destroy
    @market.destroy
    respond_to do |format|
      format.html { redirect_to markets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_market
      @market = Market.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def market_params
      params.require(:market).permit(:name, :ip, :port, :fix_HeartBtInt, :fix_BeginString, :fix_TargetCompID)
    end
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/views/markets/_form.html.erb
<%= form_for(@market) do |f| %>
  <% if @market.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@market.errors.count, "error") %> prohibited this market from being saved:</h2>

      <ul>
      <% @market.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ip %><br>
    <%= f.text_field :ip %>
  </div>
  <div class="field">
    <%= f.label :port %><br>
    <%= f.number_field :port %>
  </div>
  <div class="field">
    <%= f.label :fix_HeartBtInt %><br>
    <%= f.number_field :fix_HeartBtInt %>
  </div>
  <div class="field">
    <%= f.label :fix_BeginString %><br>
    <%= f.text_field :fix_BeginString %>
  </div>
  <div class="field">
    <%= f.label :fix_TargetCompID %><br>
    <%= f.text_field :fix_TargetCompID %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/markets/edit.html.erb
<h1>Editing market</h1>

<%= render 'form' %>

<%= link_to 'Show', @market %> |
<%= link_to 'Back', markets_path %>

app/views/markets/index.html.erb
<h1>Listing markets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ip</th>
      <th>Port</th>
      <th>HeartBtInt</th>
      <th>BeginString</th>
      <th>TargetCompID</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @markets.each do |market| %>
      <tr>
        <td><%= market.name %></td>
        <td><%= market.ip %></td>
        <td><%= market.port %></td>
        <td><%= market.fix_HeartBtInt %></td>
        <td><%= market.fix_BeginString %></td>
        <td><%= market.fix_TargetCompID %></td>
        <td><%= link_to 'Show', market %></td>
        <td><%= link_to 'Edit', edit_market_path(market) %></td>
        <td><%= link_to 'Destroy', market, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Market', new_market_path %>

app/views/markets/new.html.erb
<h1>New market</h1>

<%= render 'form' %>

<%= link_to 'Back', markets_path %>

app/views/markets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @market.name %>
</p>

<p>
  <strong>Ip:</strong>
  <%= @market.ip %>
</p>

<p>
  <strong>Port:</strong>
  <%= @market.port %>
</p>

<p>
  <strong>Fix heartbtint:</strong>
  <%= @market.fix_HeartBtInt %>
</p>

<p>
  <strong>Fix beginstring:</strong>
  <%= @market.fix_BeginString %>
</p>

<p>
  <strong>Fix targetcompid:</strong>
  <%= @market.fix_TargetCompID %>
</p>

<%= link_to 'Edit', edit_market_path(@market) %> |
<%= link_to 'Back', markets_path %>