config/routes.rb
Quanthicaweb::Application.routes.draw do

  resources :user_algorithm_subscriptions

  resources :brokers

  resources :markets

  resources :api_calls, except: [:new, :edit, :update]

  mount API::Base => '/api'
    
  resources :algorithms

  resources :profiles

  root to: "static_pages#home", via: [:get]
  match '/about', to: 'static_pages#about', via: [:get]
  match '/register_email', to: 'static_pages#register_email', via: [:post]
    
  devise_for :users
  scope '/admin' do
    resources :users
    resources :roles
  end
  

end

app/models/broker.rb
class Broker < ActiveRecord::Base
  
  validates_uniqueness_of :name
  validates_presence_of :name
  validates_presence_of :market_password_digest

  before_save :encrypt_password, if: :market_password_digest_changed?

  belongs_to :market

  def encrypt_password
    crypt = ActiveSupport::MessageEncryptor.new(Quanthicaweb::Application.config.secret_key_base)
    self.market_password_digest = crypt.encrypt_and_sign(market_password_digest) # unless market_password_digest.blank?
  end

  def decrypt_password_digest
    crypt = ActiveSupport::MessageEncryptor.new(Quanthicaweb::Application.config.secret_key_base)
    crypt.decrypt_and_verify(market_password_digest)
  end

end

app/controllers/brokers_controller.rb
class BrokersController < ApplicationController

  load_and_authorize_resource
  before_action :set_broker, only: [:show, :edit, :update, :destroy]

  # GET /brokers
  # GET /brokers.json
  def index
    @brokers = Broker.all
  end

  # GET /brokers/1
  # GET /brokers/1.json
  def show
  end

  # GET /brokers/new
  def new
    @broker = Broker.new
  end

  # GET /brokers/1/edit
  def edit
  end

  # POST /brokers
  # POST /brokers.json
  def create
    @broker = Broker.new(broker_params)

    respond_to do |format|
      if @broker.save
        format.html { redirect_to @broker, notice: 'Broker was successfully created.' }
        format.json { render action: 'show', status: :created, location: @broker }
      else
        format.html { render action: 'new' }
        format.json { render json: @broker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brokers/1
  # PATCH/PUT /brokers/1.json
  def update
    respond_to do |format|
      if @broker.update(broker_params)
        format.html { redirect_to @broker, notice: 'Broker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @broker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brokers/1
  # DELETE /brokers/1.json
  def destroy
    @broker.destroy
    respond_to do |format|
      format.html { redirect_to brokers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_broker
      @broker = Broker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def broker_params
      params[:broker][:market_password_digest] = params[:password_changed] unless params[:password_changed].blank?
      params.require(:broker).permit(:name, :email, :market_username, :market_password_digest, :market_id, :fix_SenderCompID)
    end
end

app/helpers/brokers_helper.rb
module BrokersHelper
end

app/views/brokers/_form.html.erb
<%= form_for(@broker) do |f| %>
  <%= render 'shared/form_error_message_listing', object: f.object %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :market_username %><br>
    <%= f.text_field :market_username %>
  </div>
  <div class="field">
    <%= f.label :market_password_digest %><br>
    <%= text_field_tag 'password_changed' %>
    <%= f.hidden_field :market_password_digest %>
  </div>
  <div class="field">
    <%= f.label :market_id %><br>
    <%= f.collection_select :market_id, Market.order('name ASC'), :id, :name, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :fix_SenderCompID %><br>
    <%= f.text_field :fix_SenderCompID %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brokers/edit.html.erb
<h1>Editing broker</h1>

<%= render 'form' %>

<%= link_to 'Show', @broker %> |
<%= link_to 'Back', brokers_path %>

app/views/brokers/index.html.erb
<h1>Listing brokers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Market username</th>
      <th>Market</th>
      <th>SenderCompID</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @brokers.each do |broker| %>
      <tr>
        <td><%= broker.name %></td>
        <td><%= broker.email %></td>
        <td><%= broker.market_username %></td>
        <td><%= broker.market.name unless broker.market_id.nil? %></td>
        <td><%= broker.fix_SenderCompID %></td>
        <td><%= link_to 'Show', broker %></td>
        <td><%= link_to 'Edit', edit_broker_path(broker) %></td>
        <td><%= link_to 'Destroy', broker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Broker', new_broker_path %>

app/views/brokers/new.html.erb
<h1>New broker</h1>

<%= render 'form' %>

<%= link_to 'Back', brokers_path %>

app/views/brokers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @broker.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @broker.email %>
</p>

<p>
  <strong>Market username:</strong>
  <%= @broker.market_username %>
</p>

<p>
  <strong>Market password digest:</strong>
  <%= @broker.market_password_digest %>
</p>

<p>
  <strong>Market:</strong>
  <%= @broker.market.name unless @broker.market_id.nil? %>
</p>

<p>
  <strong>Fix sendercompid:</strong>
  <%= @broker.fix_SenderCompID %>
</p>

<%= link_to 'Edit', edit_broker_path(@broker) %> |
<%= link_to 'Back', brokers_path %>